# This Notebook will be for writing codes for basic ML like loss functions, optimization functions, etc.. 

### SVM Loss 

Required:
1. Weight matrix
2. Sample input data
3. bias vector

Methods:
1. Loss calculate:

    a. Non - vectorized
    b. Half - Vectorized
    c. Full - Vectorized

In [80]:
import numpy as np

In [81]:
def Debug(desc, value):
    print "\n" + desc +  "\n"
    print value

In [85]:
# Inputs: 
# @y : 1 x N (ground truth labels)
# @wts : C x D (class x feature dim)
# @datapts : => D x N (features x data points)
# @bias : C x 1

# output:
# loss : SVM loss

# TODO: 
# 1. bias can be incorporated inside wts itself by creating one more column vector and corresponding change in datapts.

def svm_loss(wts, datapts, y, bias):
    # TODO: check dim of matrices
    scores = np.add((np.dot(wts, datapts)), bias);  # bias will be broadcasted
    Debug("Scores: ", scores)
    
    loss_vec = np.zeros(y.size)
    delta = 1.0
    
    ## No vectorization ##
    '''
    # loop for each data point
    for i in range(y.size):
        loss_i = 0;
        correct_label = y[i]
        correct_class_score = scores[correct_label, i]

        # loop for number of classes
        for j in range(scores.shape[0]):
            if(correct_label != j):
                hinge_loss_i_j = max(scores[j, i] - correct_class_score + delta, 0)
                loss_i += hinge_loss_i_j       
        
        loss_vec[i] = loss_i
    '''
    
    ## Half - vectorized  ##
    '''
    for i in range(y.size):
        loss_i = 0;
        correct_class_score = scores[y[i], i]
                
        loss_margins = np.maximum(0, scores[:, i] - correct_class_score + delta)
        loss_margins[y[i]] = 0   # for correct class margin is 0
        print "\nLoss Margin: \n"
        print loss_margins
        
        loss_i = np.sum(loss_margins)        
        
        loss_vec[i] = loss_i
    '''
    
    ##  FULL VECTORIZED ##
    ''
    #scores_mat = np.repeat(scores[:, np.newaxis], scores.size, axis=1)
    #print "\nScores Repeated: \n"
    #print scores_mat
    
    correct_score_mat = scores[y, np.arange(scores.shape[1])]   # 1 x N
    Debug("Correct Label Scores:", correct_score_mat)
    
    loss_margin = np.maximum(scores - correct_score_mat + delta, 0)
    loss_margin[y, np.arange(loss_margin.shape[1])] = 0     # Making loss of actual labels 0
    Debug("Loss Margin: ", loss_margin)
    
    loss_vec = np.sum(loss_margin, axis=0)
    ''
    
    
    return loss_vec

In [86]:
def test_svm_loss():
    #wts = np.random.random((3,4))
    wts = np.array([ [  1,   5,   9,   9],
                     [  6,   3,   3,   6],
                     [  7,   5,   8,   9]
                    ])
    Debug("Weights:", wts)
    
    datapts = np.array([[2, 1, 4, 3],
                       [5, 8, 2, 9],
                       [11, 4, 1, 6],
                       [7, 3, 6, 5]
                       ])
    Debug("Data:", datapts)
    
    bias = 0 #np.ones(datapts.size - 1)
    
    y = np.array([1, 0, 2, 1])
    
    loss = svm_loss(wts, datapts, y, bias)
    Debug("Loss:", loss)


In [87]:
test_svm_loss()


Weights:

[[1 5 9 9]
 [6 3 3 6]
 [7 5 8 9]]

Data:

[[ 2  1  4  3]
 [ 5  8  2  9]
 [11  4  1  6]
 [ 7  3  6  5]]

Scores: 

[[189 104  77 147]
 [102  60  69  93]
 [190 106 100 159]]

Correct Label Scores:

[102 104 100  93]

Loss Margin: 

[[ 88.   0.   0.  55.]
 [  0.   0.   0.   0.]
 [ 89.   3.   0.  67.]]

Loss:

[ 177.    3.    0.  122.]


array([[ 0.21390293,  0.20527074],
       [ 0.03523754,  0.59695323],
       [ 0.55960165,  0.95692197]])