In [1]:
import numpy as np

In [2]:
a = np.random.random((2,3))

In [ ]:
a

In [ ]:
a.T

In [21]:
#import pdb; pdb.set_trace()
b = np.array([20, 30, 40])
c = np.array([1, 2, 3])
print c
d = b-c
d

[1 2 3]


array([19, 28, 37])

In [ ]:
b.size

In [25]:
np.repeat(c[:, np.newaxis], 3, axis = 1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])